version: "3.7"


services:
    app:
        build:
            context: ./docker-compose/php-fpm
        volumes:
            - ~/.ssh:/home/${USER}/.ssh:rw
            - ./:/var/www
        depends_on:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./var/lib/mysql
        ports:
            - "3307:3306"

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
